/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeNewRouteImport } from './routes/trade.new'
import { Route as ApiMetaapiSyncRouteImport } from './routes/api.metaapi-sync'
import { Route as ApiEaWebhookRouteImport } from './routes/api.ea-webhook'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeNewRoute = TradeNewRouteImport.update({
  id: '/trade/new',
  path: '/trade/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaapiSyncRoute = ApiMetaapiSyncRouteImport.update({
  id: '/api/metaapi-sync',
  path: '/api/metaapi-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEaWebhookRoute = ApiEaWebhookRouteImport.update({
  id: '/api/ea-webhook',
  path: '/api/ea-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trades': typeof TradesRoute
  '/api/ea-webhook': typeof ApiEaWebhookRoute
  '/api/metaapi-sync': typeof ApiMetaapiSyncRoute
  '/trade/new': typeof TradeNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trades': typeof TradesRoute
  '/api/ea-webhook': typeof ApiEaWebhookRoute
  '/api/metaapi-sync': typeof ApiMetaapiSyncRoute
  '/trade/new': typeof TradeNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trades': typeof TradesRoute
  '/api/ea-webhook': typeof ApiEaWebhookRoute
  '/api/metaapi-sync': typeof ApiMetaapiSyncRoute
  '/trade/new': typeof TradeNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/trades'
    | '/api/ea-webhook'
    | '/api/metaapi-sync'
    | '/trade/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/trades'
    | '/api/ea-webhook'
    | '/api/metaapi-sync'
    | '/trade/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/trades'
    | '/api/ea-webhook'
    | '/api/metaapi-sync'
    | '/trade/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TradesRoute: typeof TradesRoute
  ApiEaWebhookRoute: typeof ApiEaWebhookRoute
  ApiMetaapiSyncRoute: typeof ApiMetaapiSyncRoute
  TradeNewRoute: typeof TradeNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/new': {
      id: '/trade/new'
      path: '/trade/new'
      fullPath: '/trade/new'
      preLoaderRoute: typeof TradeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metaapi-sync': {
      id: '/api/metaapi-sync'
      path: '/api/metaapi-sync'
      fullPath: '/api/metaapi-sync'
      preLoaderRoute: typeof ApiMetaapiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ea-webhook': {
      id: '/api/ea-webhook'
      path: '/api/ea-webhook'
      fullPath: '/api/ea-webhook'
      preLoaderRoute: typeof ApiEaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TradesRoute: TradesRoute,
  ApiEaWebhookRoute: ApiEaWebhookRoute,
  ApiMetaapiSyncRoute: ApiMetaapiSyncRoute,
  TradeNewRoute: TradeNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
